# Generated by Django 6.1.1 on 2026-09-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Resolved', 'Resolved')], default='Unread', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
